### ISSUE TITLE
Implement retries?

### ISSUE THREAD

**Issue by eldargab** [tmcgroul/ape-subsquid#1]
https://github.com/subsquid/ape-subsquid/blob/be995e05875e84483a58328e1ae73b86f91fd14f/ape_subsquid/query.py#L191

By design few minute archive outages are normal. It makes sense to implement request retries with a proper user notification explaining what is happening and why. 

Or is it done by the framework already?

**Comment by tmcgroul** [comment]
correct. archive outages could be problmatic especially for long running queries.
i thought about that problem but decided to make sure that plugin is used by somebody before i add retries 🤔

**Comment by tmcgroul** [comment]
implemented here - https://github.com/subsquid/ape-subsquid/commit/f53db9fb0e713ade4afb354ffd70735c400f816c

**Comment by eldargab** [comment]
@tmcgroul , that's not a very good retry strategy. It is better to retry `get_worker -> query` sequence as a whole.

**Comment by tmcgroul** [comment]
@eldargab sure! like that? - https://github.com/subsquid/ape-subsquid/commit/907c623e27119a0066c0d0ef3d02ae5abbbbd7b7
