### ISSUE TITLE
Add `createResultAddress` filter to archive?

### ISSUE THREAD

**Issue by eldargab** [tmcgroul/ape-subsquid#2]
https://github.com/subsquid/ape-subsquid/blob/be995e05875e84483a58328e1ae73b86f91fd14f/ape_subsquid/query.py#L130

`createResultAddress` filter is very easy to implement and will make this query much faster.

**Comment by tmcgroul** [comment]
implemented here - https://github.com/subsquid/ape-subsquid/commit/9aaa29174590e1875d074f18e8cde137f0e24ec3
